

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  thymeleaf:
    cache: false
logging:
  level:
    org:
      hibernate:
        type: trace